application: mosquelando
version: 2
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"

- name: setuptools
  version: "0.6c11"

handlers:

- url: /(.*)static(.*)
  static_files: web/\1static\2
  upload: web/.*static.*

- url: /upfile
  script: web.upfile.app

- url: /down
  script: web.down.app

- url: .*
  script: zen.gae.convention.app



